language: node_js
node_js:
  - "8.9.1"
cache:
  directories:
    - "node_modules"
addons:
  sonarcloud:
    organization: "damoresa-github"
    token:
      secure: $SONAR_TOKEN
script: npm run test:ci && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && sonar-scanner
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: ng-taskmanager-staging