language: node_js
node_js:
  - "8.9.1"
cache:
  directories:
    - "node_modules"
install: true
script: npm install && npm run test:ci && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: ng-taskmanager-staging